name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t angular-app .

      - name: Run Docker container
        id: build-app
        run: |
          docker run --name angular-container angular-app
          docker cp angular-container:/app/dist/DBpedia-Amharic-Chapter ./dist
          docker rm -f angular-container

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
 
